FaceManagement/Models/MyTag.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MyTag()
        {
            this.MyClasses = new HashSet<MyClass>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyClass> MyClasses { get; set; }
    }
}

FaceManagement/Controllers/MyTagsController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClosedXML.Excel;
using FaceManagement.Models;
using System.Data;
using FastMember;

namespace FaceManagement.Controllers
{
    [Authorize]
    public class MyTagsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        FaceIDEntities db = new FaceIDEntities();

        public JsonResult getAll()
        {
            var tags = db.MyTags.Where(t => t.User == User.Identity.Name).ToList();
            tags.ForEach(t => t.MyClasses.Clear());
            return Json(tags, JsonRequestBehavior.AllowGet);
        }

        public JsonResult getById(int id)
        {
            var tag = db.MyTags.Find(id);
            tag.MyClasses.Clear();
            return Json(tag, JsonRequestBehavior.AllowGet);
        }

        public string create(MyTag tag)
        {
            if (tag != null)
            {
                try
                {
                    tag.User = User.Identity.Name;
                    db.MyTags.Add(tag);
                    db.SaveChanges();
                    return "Tag Created";
                }
                catch (Exception e)
                {
                    return e.GetBaseException().Message;
                }
            }
            else return "Invalid Tag";
        }

        public string update(MyTag model)
        {
            if (model != null)
            {
                try
                {
                    var tag = db.MyTags.Find(model.id);
                    tag.Name = model.Name;
                    db.SaveChanges();
                    return "Tag Updated";
                }
                catch (Exception e)
                {
                    return e.GetBaseException().Message;
                }
            }
            else return "Invalid Tag";
        }

        public string delete(int id)
        {
            try
            {
                var tag = db.MyTags.Find(id);
                db.MyClasses.RemoveRange(tag.MyClasses);
                db.MyTags.Remove(tag);
                db.SaveChanges();
                return "Tag Deleted";
            }
            catch (Exception e)
            {
                return e.GetBaseException().Message;
            }
        }

        public FileResult download(int id)
        {
            UrlHelper url = new UrlHelper(Request.RequestContext);
            using (var workbook = new XLWorkbook())
            {
                var model = db.MyTags.Find(id);
                foreach (var item in model.MyClasses)
                {
                    var data = db.CheckIns.Where(c => c.Class_id == item.id).ToList().Select(c => new
                    {
                        Order = c.id,
                        Date = c.date,
                        Code = c.Code,
                        Image = String.Format("{0}App_Data/Checks/{1}/{2}.jpg{3}", url.Action("Index", "Home", null, Request.Url.Scheme), item.id, c.Code,
                                                c.Code != c.Email ? String.Format(" (by {0})", c.Email) : null),
                        Accuracy = c.Accuracy
                    });
                    var table = new DataTable();
                    using (var reader = ObjectReader.Create(data))
                        table.Load(reader);
                    workbook.Worksheets.Add(table, Escape(item.Title));
                }
                var memory = new MemoryStream();
                workbook.SaveAs(memory);
                return File(memory.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", Escape(model.Name) + ".xlsx");
            }
        }

        private string Escape(string name)
        {
            foreach (var c in @":\/?*[]")
                name = name.Replace(c, '_');
            return name;
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

FaceManagement/Views/MyTags/Index.cshtml
<div ng-app="myTags">
    <h1>My Tags</h1>
    <div ng-controller="tagController">
        <input type="button" value="Add Tag" ng-click="addTag()" style="float:right" />
        <div ng-show="divTag">
            <table>
                <tr>
                    <td><b>Name</b></td>
                    <td>
                        <input type="text" ng-model="tagName" required />
                    </td>
                    <td>
                        <input type="hidden" ng-model="tagId" />
                        <input type="button" value="Save" ng-click="AddEditTag()" />
                    </td>
                </tr>
            </table>
        </div>
        <table class="table table-bordered table-hover">
            <tr>
                <td><b>Name</b></td>
                <td>Actions</td>
            </tr>
            <tr ng-repeat="tag in myTags">
                <td>
                    {{tag.Name}}
                </td>
                <td>
                    <button ng-click="editTag(tag)">Edit</button>
                </td>
            </tr>
        </table>
    </div>
</div>
    
@section Scripts {
    <script>
        angular.module("myTags", []).service('tagService', function ($http) {
            this.getTags = function () {
                return $http.get('@Url.Action("getAll", "MyTags")');
            }
            this.getTag = function (tagId) {
                var response = $http({
                    method: 'post',
                    url: '@Url.Action("getById", "MyTags")',
                    params: {
                        id: tagId
                    }
                });
                return response;
            }
            this.addTag = function (tag) {
                var response = $http({
                    method: 'post',
                    url: '@Url.Action("create", "MyTags")',
                    data: JSON.stringify(tag),
                    dataType: 'json'
                });
                return response;
            }
            this.editTag = function (tag) {
                var response = $http({
                    method: 'post',
                    url: '@Url.Action("update", "MyTags")',
                    data: JSON.stringify(tag),
                    dataType: 'json'
                });
                return response;
            }
        }).controller('tagController', function ($scope, tagService) {
            $scope.divTag = false;
            getAllTags();
            function getAllTags() {
                var getData = tagService.getTags();
                getData.then(function (tags) {
                    $scope.myTags = tags.data;
                }, function () {
                    alert('Error in getting MyTags records');
                });
            }
            $scope.addTag = function () {
                clearFields();
                $scope.action = 'add';
                $scope.divTag = true;
            }
            $scope.editTag = function (tag) {
                var getData = tagService.getTag(tag.id);
                getData.then(function (tag) {
                    $scope.tagId = tag.data.id;
                    $scope.tagName = tag.data.Name;
                    $scope.action = 'edit';
                    $scope.divTag = true;
                }, function () {
                    alert('Error in getting MyTags records');
                });
            }
            $scope.AddEditTag = function () {
                var tag = {
                    Name: $scope.tagName
                }
                var getAction = $scope.action;
                if (getAction == 'add') {
                    var getData = tagService.addTag(tag);
                    getData.then(function (msg) {
                        getAllTags();
                        alert(msg.data);
                        $scope.divTag = false;
                    }, function () {
                        alert('Error in getting MyTags records');
                    });
                } else {
                    tag.id = $scope.tagId;
                    var getData = tagService.editTag(tag);
                    getData.then(function (msg) {
                        getAllTags();
                        alert(msg.data);
                        $scope.divTag = false;
                    }, function () {
                        alert('Error in getting MyTags records');
                    });
                }
            }
            function clearFields() {
                $scope.tagId = '';
                $scope.tagName = '';
            }
        });
    </script>
}